firstapp/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views


urlpatterns = [
    path("", views.Index.as_view(), name="index"),
    path("contactus/", views.ContactUs.as_view(), name="contactus"),

    
    path("signup/", views.RegisterViewBasic.as_view(), name="signup"),
    path("login/", views.LoginViewUser.as_view(), name="login"),
    path("signupseller/", views.RegisterViewSeller.as_view(), name="signupseller"),
    path("logout/", views.LogoutViewUser.as_view(), name="logout"),


    #path("cart/", )
]

firstproject/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('firstapp.urls', 'firstapp'), namespace='firstapp')),

]

firstapp/models.py
from django.db import models

from django.core.validators import RegexValidator
from django.utils import timezone
from django.contrib.auth.models import User

from multiselectfield import MultiSelectField

from django.contrib.auth.models import AbstractUser, AbstractBaseUser
from django.utils.translation import ugettext_lazy as _

from .managers import CustomUserManager

from django.contrib.auth.models import PermissionsMixin

from django.db.models import Q


class CustomUser(AbstractBaseUser, PermissionsMixin):
    email = models.EmailField(_('email address'), unique=True)
    name = models.CharField(max_length=255, default="")
    is_staff = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    date_joined = models.DateTimeField(default=timezone.now)

    # WITH HELP OF BOOLEAN FIELD
    # is_customer = models.BooleanField(default=True)
    # is_seller = models.BooleanField(default=False)

    # type = (
    #     (1, 'SELLER'),
    #     (2, 'Customer')
    # )
    # user_type = models.IntegerField(choices=type, default=1)

    # usertype = models.ManyToManyField(UserType)    

    class Types(models.TextChoices):
        SELLER = "Seller", "SELLER"
        CUSTOMER = "Customer", "CUSTOMER"


    default_type = Types.CUSTOMER

    #type = models.CharField(_('Type'), max_length=255, choices=Types.choices, default=default_type)
    type = MultiSelectField(choices=Types.choices, default=[], null=True, blank=True)


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = CustomUserManager()

    def __str__(self):
        return self.email

    # if the code is not below then accessing default values in User model not in proxy models
    def save(self, *args, **kwargs):
        if not self.id:
            #self.type = self.default_type
            self.type.append(self.default_type)
        return super().save(*args, **kwargs)


class CustomerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    address = models.CharField(max_length=500)

    def __str__(self):
        return self.user.email


class SellerAdditional(models.Model):
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    gst = models.CharField(max_length=10)
    warehouse_location = models.CharField(max_length=500)

    def __str__(self):
        return self.user.email


# Created custom query_set // Model managers for the proxy models
class SellerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.SELLER)
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains = CustomUser.Types.SELLER))

class CustomerManager(models.Manager):
    def get_queryset(self, *args, **kwargs):
        #return super().get_queryset(*args, **kwargs).filter(type = CustomUser.Types.CUSTOMER)
        return super().get_queryset(*args, **kwargs).filter(Q(type__contains = CustomUser.Types.CUSTOMER))


# Proxy Models ::: They do not create a seperate table
class Seller(CustomUser):
    default_type = CustomUser.Types.SELLER
    objects = SellerManager()

    class Meta:
        proxy = True
    
    def sell(self):
        print("I can sell")
    
    @property
    def showAdditional(self):
        return self.selleradditional

class Customer(CustomUser):
    default_type = CustomUser.Types.CUSTOMER
    objects = CustomerManager()
    class Meta:
        proxy = True
    
    def buy(self):
        print("I can buy")
    
    @property
    def showAdditional(self):
        return self.customeradditional


class Contact(models.Model):
    email = models.EmailField()
    name = models.CharField(max_length=20, blank=True)
    phone_regex = RegexValidator(regex=r'^\+?1?\d{14}$', message="the format : '+919163862585'. Upto 14 digits allowed.")
    phone = models.CharField(max_length=255, validators=[phone_regex])
    query = models.TextField()

    def __str__(self):
        return self.email

class Product(models.Model):
    product_id = models.AutoField(primary_key=True)
    product_name = models.CharField(max_length=255)
    price = models.FloatField()

    @classmethod
    def updatePrice(cls, product_id, price):
        product = cls.objects.filter(product_id = product_id)
        product = product.first()
        product.price = price
        product.save()
        return product
    
    @classmethod
    def create(cls, product_name, price):
        product = Product(product_name=product_name, price=price)
        product.save()
        return product

    def __str__(self):
        return self.product_name

class CartManager(models.Manager):
    def create_cart(self, user):
        cart = self.create(user=user)
        #try performing more operations
        return cart

class Cart(models.Model):
    cart_id = models.AutoField(primary_key=True)
    user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
    created_on = models.DateTimeField(default=timezone.now)

    objects = CartManager()

class ProductInCart(models.Model):
    class Meta:
        unique_together = (('cart', 'product'),)
    product_in_cart_id = models.AutoField(primary_key=True)
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField()

class Order(models.Model):
    status_choices = (
        (1, 'Not Packed'),
        (2, 'Ready For Shipment'),
        (3, 'Shipped'),
        (4, 'Delivered'))
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)
    status = models.IntegerField(choices=status_choices, default=1)  

class Deal(models.Model):
    user = models.ManyToManyField(CustomUser)
    deal_name = models.CharField(max_length=255)




# Old code : Not satisfied
# class UserType(models.Model):
#     CUSTOMER = 1
#     SELLER = 2
#     TYPE_CHOICES = (
#         (SELLER, 'Seller'),
#         (CUSTOMER, 'Customer')
#     )

#     id = models.PositiveIntegerField(choices=TYPE_CHOICES, primary_key=True)

#     def __str__(self):
#         return self.get_id_display()
# class Customer(models.Model):
#     user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
#     address = models.CharField(max_length=500)

#     def __str__(self):
#         return self.user.email


# class Seller(models.Model):
#     user = models.OneToOneField(CustomUser, on_delete=models.CASCADE)
#     gst = models.CharField(max_length=10)
#     warehouse_location = models.CharField(max_length=500)

#     def __str__(self):
#         return self.user.email


# class CustomUser(AbstractUser):
#     username = None
#     email = models.EmailField(_('email address'), unique=True)

#     USERNAME_FIELD = 'email'
#     REQUIRED_FIELDS = []

#     objects = CustomUserManager()

#     def __str__(self):
#         return self.email

firstapp/forms.py
from django.contrib.auth.forms import UserCreationForm, UserChangeForm

from .models import CustomUser, Contact, Seller, SellerAdditional
from django import forms
from django.core.validators import RegexValidator

class CustomUserCreationForm(UserCreationForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class CustomUserChangeForm(UserChangeForm):

    class Meta:
        model = CustomUser
        fields = ('email',)

class ContactUsForm(forms.ModelForm):
    # email = forms.EmailField(required=True)
    # name = forms.CharField(max_length=20, required=True)
    # phone_regex = RegexValidator(regex=r'^\+?1?\d{14}$', message="the format : '+919163862585'. Upto 14 digits allowed.")
    # phone = forms.CharField(max_length=255, required=True, validators=[phone_regex])
    # query = forms.CharField(widget=forms.Textarea)

    class Meta:
        model = Contact
        fields = [
            'email', 
            'name',
            'phone',
            'query',
        ]

class RegistrationFormBasic(UserCreationForm):
    class Meta:
        model = Seller
        fields = [
            'email',
            'name', 
            'password1',
            'password2',
        ]

# class RegistrationFormSeller(UserCreationForm):
#     gst = forms.CharField(max_length=10)
#     warehouse_location = forms.CharField(max_length=1000)

#     class Meta:
#         model = Seller
#         fields = [
#             'email',
#             'name', 
#             'password1',
#             'password2',
#             'gst',
#             'warehouse_location'
#         ]

class RegistrationFormSeller(forms.ModelForm):
    class Meta:
        model = SellerAdditional
        fields = [
            'gst',
            'warehouse_location'
        ]

firstapp/views.py
from django.shortcuts import render, HttpResponse
from django.views.generic import TemplateView, FormView, CreateView
from django.contrib.auth.views import LoginView, LogoutView
from django.contrib.auth.mixins import LoginRequiredMixin

from django.core.exceptions import ValidationError
from django.urls import reverse_lazy

from .forms import ContactUsForm, RegistrationFormBasic, RegistrationFormSeller
from .models import SellerAdditional, CustomUser


# def index(request):           // just a test function view
#     age = 10
#     arr = ['roy', 'swap', 'rhyes']
#     dic = {'a':'one', 'b':'two'}

#     return render(request, 'firstapp/index.html', {'age' : age, 'array':arr, 'dic':dic})

class Index(TemplateView):
    template_name = "firstapp/index.html"

    def get_context_data(self, **kwargs):
        age = 10
        arr = ['roy', 'swap', 'rhyes']
        dic = {'a':'one', 'b':'two'}
        context_old = super().get_context_data(**kwargs)
        context = {'age' : age, 'array':arr, 'dic':dic, 'context_old':context_old}
        return context

def contactUs(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST['phone']
        if len(phone) < 10 or len(phone) > 10:
            #return HttpResponse("Phone number should have a length of 10")
            raise ValidationError("Phone number should have a length of 10")
        email = request.POST.get('email')
        userQuery = request.POST.get('query')
        print(name + " " + phone + " " + email + " " + userQuery) 
    return render(request, 'firstapp/contactus.html')


def contactus2(request):                #contact us function based view
    if request.method == 'POST':
        form = ContactUsForm(request.POST)
        if form.is_valid():            # when this gets executed it executes cleaned_data
            if len(form.cleaned_data.get('query')) > 10:
                form.add_error('query', "Query length is not right")
                return render(request, 'firstapp/contactus2.html', {'form':form})
            form.save()
            return HttpResponse("Thank you. We will get back to you. ")
        else:
            if len(form.cleaned_data.get('query')) > 10:
                #form.add_error('query', "Query length is not right")
                form.errors['query'] = ['Query length is not right', 'It should be under 10']
            return render(request, 'firstapp/contactus2.html', {'form':form})

    return render(request, 'firstapp/contactus2.html', {'form':ContactUsForm})

class ContactUs(FormView):          # contact us class based view
    form_class = ContactUsForm
    template_name = 'firstapp/contactus2.html'
    success_url = reverse_lazy("firstapp:index")

    def form_valid(self, form):
        """
        If the form is valid, redirect to the supplied URL.
        """

        if len(form.cleaned_data.get('query')) > 10:
            form.add_error('query', "Query length is not right")
            return render(self.request, 'firstapp/contactus2.html', {'form':form})
        form.save()
        response = super().form_valid(form)
        return response
    
    def form_invalid(self, form):
        """
        If the form is invalid, render the invalid form.
        """
        if len(form.cleaned_data.get('query')) > 10:
            form.add_error('query', "Query length is not right")
            #form.errors['query'] = ['Query length should be under 10']
        response = super().form_invalid(form)
        return response


# class RegisterViewSeller(CreateView):
#     template_name = 'firstapp/register.html'
#     form_class = RegistrationForm
#     success_url = reverse_lazy('firstapp:index')

#     def post(self, request, *args, **kwargs):
#         response = super().post(request, *args, **kwargs)
#         if response.status_code == 302:
#             gst = request.POST.get('gst')
#             warehouse_location = request.POST.get('warehouse_location')
#             user = CustomUser.objects.get(email=request.POST.get('email'))
#             sell_a = SellerAdditional.objects.create(user=user, gst=gst, warehouse_location=warehouse_location)
#             return response
#         else:
#             return response


class RegisterViewBasic(CreateView):
    template_name = 'firstapp/registerBasic.html'
    form_class = RegistrationFormBasic
    success_url = reverse_lazy('firstapp:index')

class LoginViewUser(LoginView):
    template_name = 'firstapp/login.html'


class RegisterViewSeller(LoginRequiredMixin, CreateView):
    template_name = 'firstapp/registerSeller.html'
    form_class = RegistrationFormSeller
    success_url = reverse_lazy('firstapp:index')

    def form_valid(self, form):
        user = self.request.user
        user.type.append(user.Types.SELLER)
        user.save()

        form.instance.user = self.request.user
        return super().form_valid(form)

class LogoutViewUser(LogoutView):
    template_name = reverse_lazy("firstapp:index")

firstapp/templates/firstapp/base.html
<!doctype html>
<html lang="en">

<head>
	<!-- Required meta tags -->
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">

	<!-- Bootstrap CSS -->
	<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet"
		integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">

	<title>{% block title %}{% endblock %}</title>
	{% block css %}{% endblock %}

</head>

<body>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
		<div class="container-fluid">
			<a class="navbar-brand" href="/">RoyTest</a>
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse"
				data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
				aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>
			<div class="collapse navbar-collapse" id="navbarSupportedContent">
				<ul class="navbar-nav me-auto mb-2 mb-lg-0">
					<li class="nav-item">
						<a class="nav-link active" aria-current="page" href="{% url 'firstapp:index' %}">Home</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{% url 'firstapp:contactus' %}">Contact Us</a>
					</li>
					<li class="nav-item dropdown">
						<a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
							data-bs-toggle="dropdown" aria-expanded="false">
							Dropdown
						</a>
						<ul class="dropdown-menu" aria-labelledby="navbarDropdown">
							<li><a class="dropdown-item" href="#">Action</a></li>
							<li><a class="dropdown-item" href="#">Another action</a></li>
							<li>
								<hr class="dropdown-divider">
							</li>
							<li><a class="dropdown-item" href="#">Something else here</a></li>
						</ul>
					</li>
					<li class="nav-item">
						<a class="nav-link disabled" href="#" tabindex="-1" aria-disabled="true">Disabled</a>
					</li>
				</ul>
				<!--form class="d-flex">
					<input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
					<button class="btn btn-outline-success" type="submit">Search</button>
				</form> -->
				<div class="dropdown">
					<button class="btn btn-primary dropdown-toggle" type="button" id="dropdownMenuButton"
						data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
						My Account
					</button>
					<div class="dropdown-menu dropdown-menu-left" aria-labelledby="dropdownMenuButton">
						<a class="dropdown-item" href="{% url 'firstapp:signup' %}">Sign Up</a>
						<a class="dropdown-item" href="{% url 'firstapp:signupseller' %}">Sign Up Seller</a>
						<a class="dropdown-item" href="{% url 'firstapp:login' %}">Login</a>
						<a class="dropdown-item" href="{% url 'firstapp:logout' %}">Logout</a>
					</div>
				</div>
			</div>
		</div>
	</nav>
	{% block body %}
	{% endblock %}

	<!-- Option 2: Separate Popper and Bootstrap JS -->
	<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"
		integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js"
		integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous">
	</script>
	<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.0/dist/js/bootstrap.min.js"
		integrity="sha384-+YQ4JLhjyBLPDQt//I+STsc9iw4uQqACwlvpslubQzn4u2UU2UFM80nGisd026JF" crossorigin="anonymous">
	</script>
</body>
{% block js %}
{% endblock %}

</html>

firstapp/templates/firstapp/cart.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}
{% endblock %}

firstapp/templates/firstapp/contactus.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% block title %}
{% endblock %}
{% block css %}
{% endblock %}
{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <div class="mb-3">
            <label for="username" class="form-label">Name</label>
            <input type="text" name="name" class="form-control" id="username" placeholder="Your Name">
        </div>
        <div class="mb-3">
            <label for="phone" class="form-label">Phone Number</label>
            <input type="number" name="phone" class="form-control" id="phone" placeholder="Your Phone Number">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlInput1" class="form-label">Email address</label>
            <input type="email" name="email" class="form-control" id="exampleFormControlInput1"
                placeholder="name@example.com">
        </div>
        <div class="mb-3">
            <label for="exampleFormControlTextarea1" class="form-label">Any Queries?</label>
            <textarea class="form-control" name="query" id="exampleFormControlTextarea1" rows="3"></textarea>
        </div>
        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

firstapp/templates/firstapp/contactus2.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    .errorlist {
        color: red;
        font-size: 0.8em;
    }
</style>
{% endblock %}
{% block body %}
<div class="container">
    <form method="POST">
        {% csrf_token %}
        <!-- {{ form.as_p }} -->
        {{ form.non_field_errors }}
        <label for="id_email" class="login-labels">Email Address*</label>
        {{ form.email.errors }}
        {{ form.email|addClass:'form-control'|addPlaceholder:'Email Address' }}

        <label for="id_name" class="login-labels">Name </label>
        {{ form.name.errors }}
        {{ form.name|addClass:'form-control'|addPlaceholder:'Your Name' }}

        <label for="id_phone" class="login-labels">Phone No.* </label>
        {{ form.phone.errors }}
        {{ form.phone|addClass:'form-control'|addPlaceholder:'Your Phone No.' }}

        <label for="id_query" class="login-labels">Query* </label>
        {{ form.query.errors }}
        {{ form.query|addClass:'form-control'|addPlaceholder:'Any query?' }}

        <button type="submit" class="btn btn-primary">Submit</button>
    </form>
</div>
{% endblock %}

firstapp/templates/firstapp/login.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #f5f5f5;

    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: red;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}

{% block body%}
<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">
            {{ form.non_field_errors }}
            <h2 class="mainheading">Roy's Apothecary</h2>
            <h4 class="mainheading">Login</h4>
            <label for="id_username" class="login-labels">Email Address*</label>
            {{ form.username.errors }}
            {{ form.username|addClass:'form-control'|addPlaceholder:'Email Address'}}
            <label for="id_password" class="login-labels">Password*</label>
            {{ form.password.errors }}
            {{ form.password|addClass:'form-control'|addPlaceholder:'Your Password' }}
            <br>
            <div class="text-center">
                <button type="submit" class="btn btn-primary btn-lg signup-button">Login</button>
            </div>
</form>
</div>
</div>
{% endblock %}

firstapp/templates/firstapp/register.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #f5f5f5;

    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: red;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}

{% block body%}

<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">

            <h2 class="mainheading">Roy's Apothecary</h2>
            <h4 class="mainheading">Sign Up For Seller</h4>
            <p class="errorlist">{{ form.non_field_errors }}</p>
            <label for="id_email" class="login-labels">Email Address*</label>
            {{ form.email.errors }}
            {{ form.email|addClass:'form-control'|addPlaceholder:'Email Address'}}

            <label for="id_name" class="login-labels">Name*</label>
            {{ form.name.errors }}
            {{ form.name|addClass:'form-control'|addPlaceholder:'Your Name' }}
            <label for="id_password1" class="login-labels">Password*</label>
            {{ form.password1.errors }}
            {{ form.password1|addClass:'form-control'|addPlaceholder:'Your Password' }}
            <label for="id_password2" class="login-labels">Password Confirmation*</label>
            {{ form.password2.errors }}
            {{ form.password2|addClass:'form-control'|addPlaceholder:'Your Password' }}
            <label for="id_gst" class="login-labels">GST Info*</label>
            {{ form.gst.errors }}
            {{ form.gst|addClass:'form-control'|addPlaceholder:'Your GST no.' }}
            <label for="id_warehouse_location" class="login-labels">Warehouse Location*</label>
            {{ form.warehouse_location.errors }}
            {{ form.warehouse_location|addClass:'form-control'|addPlaceholder:'Warehouse Location' }}
            <br>
            <div class="text-center">
            <button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>
            </div>
</form>
</div>
</div>
{% endblock %}

firstapp/templates/firstapp/registerBasic.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #f5f5f5;

    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: red;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}

{% block body%}

<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">

            <h2 class="mainheading">Roy's Apothecary</h2>
            <h4 class="mainheading">Sign Up</h4>
            <p class="errorlist">{{ form.non_field_errors }}</p>
            <label for="id_email" class="login-labels">Email Address*</label>
            {{ form.email.errors }}
            {{ form.email|addClass:'form-control'|addPlaceholder:'Email Address'}}

            <label for="id_name" class="login-labels">Name*</label>
            {{ form.name.errors }}
            {{ form.name|addClass:'form-control'|addPlaceholder:'Your Name' }}
            <label for="id_password1" class="login-labels">Password*</label>
            {{ form.password1.errors }}
            {{ form.password1|addClass:'form-control'|addPlaceholder:'Your Password' }}
            <label for="id_password2" class="login-labels">Password Confirmation*</label>
            {{ form.password2.errors }}
            {{ form.password2|addClass:'form-control'|addPlaceholder:'Your Password' }}
            <br>
            <div class="text-center">
                <button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>
            </div>
        </div>
    </div>
</form>

{% endblock %}

firstapp/templates/firstapp/registerSeller.html
{% extends 'firstapp/base.html' %}
{% load static %}
{% load myfilters %}
{% block title %}
{% endblock %}
{% block css %}
<style>
    body {
        background-color: #f5f5f5;

    }

    .main-area {
        display: flex;
        align-items: center;
    }

    .register-form {
        width: 100%;
        max-width: 500px;
        margin: auto;
        margin-top: 40px;
        padding: 20px;
        background-color: #fff;
        border-top: 5px solid #2BA977;
        border-radius: 5px;
    }

    .mainheading {
        text-align: center;
    }

    .errorlist {
        color: red;
    }

    .signup-button {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:hover {
        background-color: #2BA977;
        border-color: #2BA977;
    }

    .signup-button:focus {
        background-color: #2BA977;
        border-color: #2BA977;
    }
</style>
{% endblock %}

{% block body%}

<form method="POST">{% csrf_token %}
    <div class="main-area">
        <div class="register-form">

            <h2 class="mainheading">Roy's Apothecary</h2>
            <h4 class="mainheading">Sign Up For Seller</h4>
            <p class="errorlist">{{ form.non_field_errors }}</p>
            <label for="id_gst" class="login-labels">GST Info*</label>
            {{ form.gst.errors }}
            {{ form.gst|addClass:'form-control'|addPlaceholder:'Your GST no.' }}
            <label for="id_warehouse_location" class="login-labels">Warehouse Location*</label>
            {{ form.warehouse_location.errors }}
            {{ form.warehouse_location|addClass:'form-control'|addPlaceholder:'Warehouse Location' }}
            <br>
            <div class="text-center">
                <button type="submit" class="btn btn-primary btn-lg signup-button">Signup</button>
            </div>
        </div>
    </div>
</form>
{% endblock %}